name: Verify and build

permissions:
  contents: write

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Validate, build and run tests
        run: mvn --batch-mode --update-snapshots verify
      - name: Prepare .jar file
        run: mkdir staging && cp target/*.jar staging
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: SortingMadness
          path: staging
      - name: Build Docker image if tagged
        uses: docker/build-push-action@v6.18.0
        if: github.ref_type == 'tag'
        with:
          file: ./Dockerfile
          tags: |
            SortingMadness
      - name: Prepare Docker image
        if: github.ref_type == 'tag'
        run: cp SortingMadness staging
      - name: Upload release if tagged
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: staging/*
